version: 2
jobs:
  build:
    working_directory: ~/circleci 
    docker:
      - image: php:7.3-apache
        environment:
          APP_ENV: test
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: APP1
          MYSQL_USER: root
          MYSQL_PASSWORD: root

        steps:
      - run:
          name: Install MySQL CLI; Import dummy data; run an example query
          command: |
            sudo apt-get install default-mysql-client
            mysql -h localhost -u root -p root APP1 < sql-data/dummy.sql
    steps:
      # - run: |
          
      - run:
          name: Install system packages
          command: apt-get update && apt-get -y install git
      - run:
          name: Install PHP extensions
          command: docker-php-ext-install pdo_mysql
      - checkout
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer invalid'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      - run:
          name: Display PHP information
          command: |
            php -v
            php composer.phar --version
      - run:
          name: update project dependencies
          command: php composer.phar update
      - run:
          name: Install project dependencies
          command: php composer.phar install
 
      - run:
          name: Run Unit tests
          command: php vendor/bin/phpunit ./TEST2/mainTest.php
 