version: 2.1

jobs:
  build:
    docker:
        - image: php:7.4-apache
          environment:
            APP_ENV: test
       
    steps:
      - checkout   
      - run: |
            apt-get update -y
            apt-get upgrade -y 
            apt-get install unzip  
            apt-get install php7.4-phpdbg
      - run:
          name: Install system packages
          command: apt-get update && apt-get -y install git
      - run:
          name: Install PHP extensions
          command: docker-php-ext-install pdo_mysql
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer invalid'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      - run:
          name: Display PHP information
          command: |
            php -v
            php composer.phar --version
      - run:
          name: update project dependencies
          command: php composer.phar update
      - run:
          name: Install project dependencies
          command: php composer.phar install
      - run: 
          name: installing Xdebug for PHP
          command: |
            php -version
            apt-get install phpdbg
           
      - run:
          name: "Coverage reports"
          command: phpdbg -qrr vendor/bin/phpunit --coverage-html build/coverage-report ./TEST2/mainTest.php
          environment:
            XDEBUG_MODE: coverage
      - store_artifacts:
          path:  build/coverage-report
      - run:
          name: Run Unit tests
          command: |
           php vendor/bin/phpunit ./TEST2/mainTest.php
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
 
